### ISSUE TITLE
Self-hosting fails

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#1]
When I try to ncc ncc:

```
▲  ncc/ (master) ncc index.js
(node:22762) UnhandledPromiseRejectionWarning: Error: 'sync' is not exported by node_modules/resolve/index.js
    at error (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:12726:29)
    at FunctionScope.Scope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:4022:68)
    at BlockScope.Scope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:4022:68)
    at FunctionScope.Scope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:4022:68)
(node:22762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by guybedford** [comment]
I've confirmed that this bug is fixed by https://github.com/rollup/rollup-pluginutils/pull/44.

After that, the execution bug then becomes the standard cycles bug on streams I believe.
