### ISSUE TITLE
`twilio` errors

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#10]
ncc version: 0.0.4

Source:

```js
const twilio = require('twilio')
const client = new twilio('a', 'b');
```

Crashes with:

```
▲  twilio/ node out.js
tough-cookie: can't load punycode; won't use punycode for domain normalization
util.js:291
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:291:11)
    at Object.<anonymous> (/Users/rauchg/Projects/now-demos/twilio/out.js:1:1505162)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

**Comment by guybedford** [comment]
As mentioned, I believe this is the tougher circular reference issue, and there may be a few approaches to this. Will put some thought to this as the priority then.

**Comment by rauchg** [comment]
Also happening with `postmark` as reported by @joecohens 

```
tough-cookie: can't load punycode; won't use punycode for domain normalization
util.js:291
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:291:11)
    at Object.<anonymous> (/Users/rauchg/Projects/play-ncc/postmark/postmark.js:1:294079)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```
