### ISSUE TITLE
Regression on master / 0.8.0

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#178]
```
Error: Hash: daa715eaf4f1a1626f9b
Version: webpack 5.0.0-next
Time: 6463ms
Built at: 12/19/2018 8:22:31 PM
Entrypoint main =
 [49] ./node_modules/twilio/lib/jwt/taskrouter/TaskRouterCapability.js 3.1 KiB {404} [built]
 [64] external "util" 42 bytes {404} [built]
[179] ./node_modules/twilio/lib/twiml/VoiceResponse.js 69 KiB {404} [built]
[245] ./node_modules/twilio/lib/jwt/taskrouter/util.js 4.26 KiB {404} [built]
[306] ./twilio.js 38 bytes {404} [built]
[449] ./node_modules/twilio/lib/twiml/FaxResponse.js 1.26 KiB {404} [built]
[512] ./node_modules/twilio/package.json 1.35 KiB {404} [built]
[522] ./node_modules/twilio/lib/base/obsolete.js 1.54 KiB {404} [built]
[531] ./node_modules/lodash/lodash.js 527 KiB {404} [built]
[622] ./node_modules/twilio/lib/rest/Twilio.js 16.5 KiB {404} [built]
[699] ./node_modules/twilio/lib/jwt/ClientCapability.js 3.6 KiB {404} [built]
[749] ./node_modules/twilio/lib/jwt/AccessToken.js 8.07 KiB {404} [built]
[827] ./node_modules/twilio/lib/twiml/MessagingResponse.js 3.49 KiB {404} [built]
[885] ./node_modules/twilio/lib/webhooks/webhooks.js 6.01 KiB {404} [built]
[939] ./node_modules/twilio/lib/index.js 1.59 KiB {404} [built]
    + 720 hidden modules

ERROR in chunk main [entry]
index.js
Cannot find module 'webpack/lib/util/registerExternalSerializer'
    at F.run (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1964981)
    at t (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1912765)
    at hooks.done.callAsync.r (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1912993)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1997377), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1018888)
    at n (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1912953)
    at hooks.afterCompile.callAsync.t (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1917566)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1997377), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1018888)
    at n.seal.t (/usr/local/lib/node_modules/@zeit/ncc/dist/ncc/index.js:3:1917526)
```

**Comment by guybedford** [comment]
This should be resolved with the latest master I believe with https://github.com/zeit/ncc/pull/181 merged. But let me know if this is not the case.
