### ISSUE TITLE
@now/node fails because ncc-0.1.4-webpack

### ISSUE THREAD

**Issue by tunnckoCore** [zeit/ncc#21]
Log from the UI https://zeit.co/olstenlarck/tunnckocore-release-now-v2/agkrauawz

```
Error while initializing entrypoint: TypeError: u.startsWith is not a function
    at Object.<anonymous> (/var/task/user/index.js:152:281)
    at Object.<anonymous> (/var/task/user/index.js:153:30)
    at __webpack_require__ (/var/task/user/index.js:21:30)
    at Object.<anonymous> (/var/task/user/index.js:130:19)
    at Object.<anonymous> (/var/task/user/index.js:146:30)
    at __webpack_require__ (/var/task/user/index.js:21:30)
    at module.exports.module.exports.module.deprecate (/var/task/user/index.js:85:18)
    at Object.<anonymous> (/var/task/user/index.js:88:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by tunnckoCore** [comment]
It's probably even just after https://github.com/zeit/now-builders/commit/1443e5435bbb7b1cd0b05ba730f069c946f62857

**Comment by rauchg** [comment]
@tunnckoCore what package specifically causes this? Do you have a minimal reproduction? Can you re-open if this still happens, since it was from a few versions back?

Thank you!

**Comment by tunnckoCore** [comment]
Can think for a repro, but probably the most basic thing, starting from the example and definining `@now/node@0.1`. But anyway, I'll try it tomorrow if it is still happening. Thanks.

**Comment by tunnckoCore** [comment]
It seems it still fails. It's basically just a Probot app that I'm trying to deploy.
the status of the `now` github deployment check is green, but it seems to have error logs and does not opens the probot default app index page which usually is at `/probot`.

![2018-11-29-020158_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/49190652-f9aa1380-f37b-11e8-88bb-a72e9276d61e.png)

**Comment by rauchg** [comment]
What dependency is the one that ends up causing the issue @tunnckoCore ?

**Comment by tunnckoCore** [comment]
I'm not sure what you mean. But I'm using `@now/node` builder.

**Comment by igorklopov** [comment]
`tunnckocore-release-now-v2` uses `esm` npm package. `esm` assumes that `module.id` is a string https://github.com/standard-things/esm/blob/880e03105f20d767d49b620717a2c78888ff2aa7/esm.js#L29, particularly calls it's `startsWith` method. In pure node.js env it is true - `module.id` in a string indeed. But when webpacked, that `id` is a number. You can test it by nccing `console.log(typeof module.id, module.id);`. A solution can be replacing `module.i` with `String(module.i)` in https://github.com/webpack/webpack/blob/e3e8a68dabc102d7f67fd4c5584baf293b21cddf/buildin/module.js#L16.

**Comment by tunnckoCore** [comment]
Hm. Sounds like it should be fixed there, but a temporary workaround for me would be to remove the `esm`.

Btw, the problem more of is that `ncc` is force-using the `main` instead of `module`. I definitely am not sure why this should be that way. But if it works as normal then the webpack will just resolve the `src/index.js` (which is the `module` field) instead of the `esm` bridge that i create. And I follow that pattern for all my repos and publishing packages.

**Comment by igorklopov** [comment]
@tunnckoCore afaiu you use `index.js` explicitly in your `now.json` file. So `ncc` uses it as entrypoint for compiling your project. Can you please try specifying `src/index.js` and see what happens.

**Comment by tunnckoCore** [comment]
Hm. Make sense, yea. I'll try.

One more thought, can we define `src: "."` instead and so, it will search `main` and `module` fields from the package.json?

**Comment by tunnckoCore** [comment]
Strangely, `src/index.js` not works. It even does not build and no logs.

**Comment by tunnckoCore** [comment]
OKey, `src/index.js` works. But still, can someone explain to me why we forcing to use `main`?

**Comment by igorklopov** [comment]
What makes you think we use entries of `package.json`? `@now/node` indeed uses package.json to install dependencies. But it does not use neither `main`, nor `module`, nor `bin`. You specify javascript file as `src` bypassing package.json and it's `main` entry. Correct me if i am wrong.

**Comment by igorklopov** [comment]
But seems you are right https://github.com/zeit/ncc/blob/ab31c82196e3157f3538aaebaf8809310b3ac794/src/index.js#L67

**Comment by tunnckoCore** [comment]
Yes, it forces Webpack to use `main` instead it's default resolution `module, main`, and there was a code comment about that before when I looked at the code.

**Comment by rauchg** [comment]
@tunnckoCore that's the intent of this project. It's for Node.js codebases. Node doesn't support `module`. I'm re-opening as we definitely need to fix the `module.id` thing, which Node does support :)

**Comment by tunnckoCore** [comment]
> Node doesn't support module. 

You meant ESM? It partially supports and will support in future. Also it worth nothing to make `ncc` "just work" for both cjs and esm, jut by not forcing the resolving order.

Also, most of the projects already uses ESM, even without bundling, just with `esm` loader or the node's native flag (which is basically the `esm` loader under the hood). Otherwise, you people who want to use `ncc` to have two-step build: first run their build (which in most cases will be Webpack too) to make it cjs, then run `ncc`.

**Comment by tunnckoCore** [comment]
> ncc should introduce zero surprises when going from node program.js to ncc run program.js.

Got it. 

Basically, I don't need and don't want more than Nodejs v8 or v10+ and writing everything in ES Modules so it can be future proof from now, even if I die accidentally :D (bad black humor joke? ;d) I don't want build steps that's why I use `esm` loader to make it work for the cjs users. But for last 2 years I was always thinking to create similar thing to `ncc`, based on Rollup (as this started).

**Comment by guybedford** [comment]
Yeah we very specifically never want to be building "esm".

I would suggest we even mark this one as always being replaced with a "blank module".

**Comment by tunnckoCore** [comment]
Right.

Btw, we have a fix for https://github.com/standard-things/esm/issues/681 already. Next one is Webpack. :)

**Comment by tunnckoCore** [comment]
I'm opening a new issue about the `module` field, because it's not directly related to this issue.
