### ISSUE TITLE
Doesn't work with `vm2`

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#226]
```
SyntaxError: Unexpected number
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/launcher.js:10:39)
```

**Comment by guybedford** [comment]
Fixed in https://github.com/zeit/ncc/pull/231.
