### ISSUE TITLE
MJML dependency breaks the build process

### ISSUE THREAD

**Issue by bfulop** [zeit/ncc#276]
I'm trying to get a very simple repo working, with only one dependency: https://www.npmjs.com/package/mjml

As soon as I include `import mjml2html from 'mjml'` in my `date.js` file, `ncc run date.js` will fail:

```
  52kB  mime.types
 121kB  sourcemap-register.js
4272kB  index.js
4744kB  index.js.map
4445kB  [8914ms]

/private/var/folders/r2/br0p741168qg5n2h65fzsdz40000gn/T/d41d8cd98f00b204e9800998ecf8427e/index.js:66898
	var e = new Error("Cannot find module '" + req + "'");
         ^
Error: Cannot find module '../lib/utils.js'
    at Function.webpackEmptyContext [as resolve] (/private/var/folders/r2/br0p741168qg5n2h65fzsdz40000gn/T/d41d8cd98f00b204e9800998ecf8427e/index.js:66898:10)
    at /node_modules/uglify-js/tools/node.js:17:1
    at Array.map (<anonymous>)
    at Object.3210 (/node_modules/uglify-js/tools/node.js:16:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.959 (/node_modules/html-minifier/src/htmlminifier.js:8:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.7097 (/node_modules/mjml-core/lib/index.js:61:1)
    at __webpack_require__ (/webpack:bootstrap:19:1)
    at Object.9746 (/node_modules/mjml/lib/index.js:7:1)
```

Here's a minimal repo to reproduce the issue : https://github.com/bfulop/zeitwithyarn

**Comment by bfulop** [comment]
Closing this in favour of #277, it's more focused on the root of the problem...

**Comment by bfulop** [comment]
Just for information, if anyone arrives at this issue, the [test repo](
https://github.com/bfulop/zeitwithyarn) now works with Zeit!

The solution was to first process the code via Rollup the run the deploy.
