### ISSUE TITLE
Native module support

### ISSUE THREAD

**Issue by TooTallNate** [zeit/ncc#28]
```
$ cat index.js
const time = require('time');

const d = new time.Date();
d.setTimezone('US/Hawaii');
console.log(d.toString());

$ ncc index.js > out.js
$ node out.js
/Users/nrajlich/t/out.js:1703
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/nrajlich/t/build/time.node
 → /Users/nrajlich/t/build/Debug/time.node
 → /Users/nrajlich/t/build/Release/time.node
 → /Users/nrajlich/t/out/Debug/time.node
 → /Users/nrajlich/t/Debug/time.node
 → /Users/nrajlich/t/out/Release/time.node
 → /Users/nrajlich/t/Release/time.node
 → /Users/nrajlich/t/build/default/time.node
 → /Users/nrajlich/t/compiled/10.13.0/darwin/x64/time.node
    at bindings (/Users/nrajlich/t/out.js:1700:9)
    at Object.<anonymous> (/Users/nrajlich/t/out.js:344:39)
    at __webpack_require__ (/Users/nrajlich/t/out.js:21:30)
    at Object.<anonymous> (/Users/nrajlich/t/out.js:326:14)
    at __webpack_require__ (/Users/nrajlich/t/out.js:21:30)
    at /Users/nrajlich/t/out.js:85:18
```

However, even if I manually copy over the `.node` file into `./build/time.node`, I get the same error. I think due to some webpack magic related to dynamic require calls. Webpack turns this:

```js
      b = opts.path ? require.resolve(n) : require(n)
```

Into this:

```js
      b = opts.path ? /*require.resolve*/(__webpack_require__(3).resolve(n)) : __webpack_require__(3)(n)
```

**Comment by TooTallNate** [comment]
Note that for native addons that use the `bindings` module, [this _seems_ to work](https://github.com/TooTallNate/node-bindings/commit/40dcc1ffd085e22cf4b730a002ceeed77297ac5), however I'm not sure if packer-specific hacks belong in that module vs. being handled here in the configuration.

Then there's also the question of moving the relevant `.node` files into `./build` dir relative to the output webpack bundle file, but that's more related to `@now/node` and not `ncc` specifically.

**Comment by rauchg** [comment]
Closing in favor of #57
