### ISSUE TITLE
"ncc run" doesn't work with shebang

### ISSUE THREAD

**Issue by sheerun** [zeit/ncc#285]
Example error output:

```
 121kB  sourcemap-register.js
1700kB  index.js
2026kB  index.js.map
1821kB  [1323ms] - ncc 0.15.1
/private/var/folders/22/xz6_9gpx3jggts_8j68_25g80000gn/T/d41d8cd98f00b204e9800998ecf8427e/index.js:1
(function (exports, require, module, __filename, __dirname) { require('./sourcemap-register.js');#!/usr/bin/env node
                                                                                                 ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by guybedford** [comment]
Thanks for reporting, fix created in https://github.com/zeit/ncc/pull/286.

**Comment by sheerun** [comment]
Thank you :)
