### ISSUE TITLE
node-zstd doesn't work

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#288]
Reproduction: https://github.com/mscoutermarsh/now-zstd

**Comment by guybedford** [comment]
More info on the replication would help here:

* The repo at https://github.com/mscoutermarsh/now-zstd has just a "hello world" index file - https://github.com/mscoutermarsh/now-zstd/blob/master/index.js
* I tried building `require('node-zstd')` and that does break, yes, but equally `node -e "require('node-zstd')"` gives the same error for me, so I'm not sure that's the replication either?

**Comment by rauchg** [comment]
CC @mscoutermarsh

**Comment by mscoutermarsh** [comment]
@guybedford thanks for looking!

I just pushed an update to `index.js` to show how I'm trying to use `node-zstd`.

```
const decompressSync = require('node-zstd').decompressSync;

module.exports = (req, res) => {
  var output = decompressSync("some zstd compressed string")
  res.end(output);
};
```

**Comment by mscoutermarsh** [comment]
Here's the error message I get on build.

```
2019-02-17T20:02:42.565Z  error /tmp/43718fa6/user/node_modules/node-zstd: Command failed.
                          Exit code: 1
                          Command: node-gyp rebuild
                          Arguments:
                          Directory: /tmp/43718fa6/user/node_modules/node-zstd
                          Output:
                          gyp info it worked if it ends with ok
                          gyp info using node-gyp@3.6.2
                          gyp info using node@8.10.0 | linux | x64
                          gyp http GET https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
                          gyp http 200 https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
                          gyp http GET https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
                          gyp http 200 https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
                          gyp info spawn /usr/bin/python
                          gyp info spawn args [ '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                          gyp info spawn args   'binding.gyp',
                          gyp info spawn args   '-f',
                          gyp info spawn args   'make',
                          gyp info spawn args   '-I',
                          gyp info spawn args   '/tmp/43718fa6/user/node_modules/node-zstd/build/config.gypi',
                          gyp info spawn args   '-I',
                          gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                          gyp info spawn args   '-I',
                          gyp info spawn args   '/tmp/.node-gyp/8.10.0/include/node/common.gypi',
                          gyp info spawn args   '-Dlibrary=shared_library',
                          gyp info spawn args   '-Dvisibility=default',
                          gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/8.10.0',
                          gyp info spawn args   '-Dnode_gyp_dir=/var/lang/lib/node_modules/npm/node_modules/node-gyp',
                          gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/8.10.0/<(target_arch)/node.lib',
                          gyp info spawn args   '-Dmodule_root_dir=/tmp/43718fa6/user/node_modules/node-zstd',
                          gyp info spawn args   '-Dnode_engine=v8',
                          gyp info spawn args   '--depth=.',
                          gyp info spawn args   '--no-parallel',
                          gyp info spawn args   '--generator-output',
                          gyp info spawn args   'build',
                          gyp info spawn args   '-Goutput_dir=.' ]
                          gyp info spawn make
                          gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
                          make: Entering directory `/tmp/43718fa6/user/node_modules/node-zstd/build'
                            CC(target) Release/obj.target/compressor/deps/zstd/lib/common/entropy_common.o
                          make: cc: Command not found
                          make: *** [Release/obj.target/compressor/deps/zstd/lib/common/entropy_common.o] Error 127
                          make: Leaving directory `/tmp/43718fa6/user/node_modules/node-zstd/build'
                          gyp ERR! build error
                          gyp ERR! stack Error: `make` failed with exit code: 2
                          gyp ERR! stack     at ChildProcess.onExit (/var/lang/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
                          gyp ERR! stack     at emitTwo (events.js:126:13)
                          gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
                          gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
                          gyp ERR! System Linux 4.14.94-89.73.amzn2.x86_64
                          gyp ERR! command "/var/lang/bin/node" "/var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
                          gyp ERR! cwd /tmp/43718fa6/user/node_modules/node-zstd
                          gyp ERR! node -v v8.10.0
                          gyp ERR! node-gyp -v v3.6.2
                          gyp ERR! not ok
```

**Comment by mscoutermarsh** [comment]
Update - I swapped to using gzip instead of zstandard. Which works great with Now.

For anyone googling this, try [zlib](https://nodejs.org/api/zlib.html):
```
const zlib = require('zlib');
```

**Comment by guybedford** [comment]
@mscoutermarsh I still get the same error when running the index file directly without ncc. The gyp error seems more of an error with node-zstd as well over ncc.

Glad to hear you found a workflow though, closing as this doesn't seem an ncc bug to me, but feel free to reopen if you have any update in future.
