### ISSUE TITLE
firebase-admin does not work

### ISSUE THREAD

**Issue by MAPESO** [zeit/ncc#305]
# Main problem 😿 

the deployment occurs without problems, however I can not connect to my database. I did an example with a node script and I was able to connect to `firestore`

I do not know why 'now' has problems with that module.

![bug](https://media.giphy.com/media/1gR46KMKx8EMSqh1BL/giphy.gif)

### How to reproduce the error 🐛 ?

**Step 1**

1. Open the Firebase  [console](https://console.firebase.google.com/?hl=es-419) and create a new project

2. In the Database section, click on Test Firestore

3. Click on enable

4. [Click](https://console.firebase.google.com/project/chat-database-ba50c/settings/serviceaccounts/adminsdk?hl=es-419) on **Generate new private key**

**Step 2**

* Create new project `mkdir example-test` 

* Create an `index.js` file

* yarn init -y

* Add the following dependency to your project: `yarn add firebase-admin`

**Step 3**

Place the following code in the file `index.js`

```js

const admin = require('firebase-admin');

const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const data = {
  name: 'Mark',
  lastName: 'Drew'
  age: 21
}

db.collection('person').doc('Mark').set(data);

```

run the following command: `DEBUG=*fun* ~/Downloads/now-macos dev --debug --port 8080`

### package.json

```json
{
  "name": "db-serverless",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "firebase-admin": "^7.0.0"
  }
}
```

**Comment by styfle** [comment]
@MAPESO We need a little more information to determine if this is a bug in `ncc`.

1. What error do you get specifically?
2. Can you provide the code from `index.js`?
3. Have you tried changing the firewall settings in your database to allow connections from any IP address? It's possible firebase is blocking Now deployments.

**Comment by MAPESO** [comment]
Hi, @styfle I just added detailed instructions to reproduce this problem ^-^

> Have you tried changing the firewall settings in your database to allow connections from any IP address? It's possible firebase is blocking Now deployments.

I have not seen any option similar to that :/

**Comment by guybedford** [comment]
I just went ahead and set up all the Firebase details here and ran the following index.js with `npm install -g ncc && ncc run index.js`:

```js
const admin = require('firebase-admin');

const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const data = {
  name: 'Mark',
  lastName: 'Drew'
  age: 21
}

db.collection('person').doc('Mark').set(data);
```

I then get the following output:

```
ncc: Module directory "/home/guybedford/Projects/ncc/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/home/guybedford/Projects/ncc/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
    1kB  protos/google/api/annotations.proto
    1kB  src/load.d.ts
    2kB  protos/update.sh
    2kB  src/index.js.map
    2kB  src/load.js.map
    2kB  src/index.d.ts
    2kB  protos/google/protobuf/empty.proto
    3kB  protos/google/firestore/v1beta1/common.proto
    3kB  protos/google/type/latlng.proto
    4kB  protos/google/rpc/status.proto
    4kB  protos/google/protobuf/struct.proto
    4kB  protos/google/protobuf/wrappers.proto
    5kB  protos/google/firestore/v1beta1/document.proto
    6kB  protos/google/protobuf/timestamp.proto
    6kB  protos/google/protobuf/any.proto
    6kB  protos/google/firestore/v1beta1/query.proto
    8kB  protos/google/firestore/v1beta1/write.proto
   15kB  protos/google/api/http.proto
   27kB  protos/google/firestore/v1beta1/firestore.proto
  121kB  sourcemap-register.js
  128kB  protos/firestore_proto_api.d.ts
  260kB  roots.pem
 7959kB  index.js
 8976kB  index.js.map
12109kB  src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node
20680kB  [7579ms] - ncc 0.15.2

The behavior for Date objects stored in Firestore is going to change
AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

  const firestore = new Firestore();
  const settings = {/* your settings... */ timestampsInSnapshots: true};
  firestore.settings(settings);

With this change, timestamps stored in Cloud Firestore will be read back as
Firebase Timestamp objects instead of as system Date objects. So you will also
need to update code expecting a Date to instead expect a Timestamp. For example:

  // Old:
  const date = snapshot.get('created_at');
  // New:
  const timestamp = snapshot.get('created_at');
  const date = timestamp.toDate();

Please audit all existing usages of Date when you enable the new behavior. In a
future release, the behavior will change to the new behavior, so if you do not
follow these steps, YOUR APP MAY BREAK.
(node:5964) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:5964) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (/tmp/google/api)
    at EventEmitter.emit (events.js:178:17)
    at EventEmitter.<anonymous> (/node_modules/walkdir/walkdir.js:217:1)
    at Object.onceWrapper (events.js:277:13)
    at EventEmitter.emit (events.js:189:13)
    at fn (/node_modules/walkdir/walkdir.js:71:1)
    at statter (/node_modules/walkdir/walkdir.js:109:1)
    at walkdir (/node_modules/walkdir/walkdir.js:221:1)
    at Function.module.exports.walkdir.sync (/node_modules/walkdir/walkdir.js:15:1)
    at module.exports.COMMON_PROTO_DIRS.map.dir (/node_modules/google-gax/build/src/grpc.js:71:1)
    at Array.map (<anonymous>)
(node:5964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The `walkdir` error above is definitely an `ncc` error, but odd that this seems different to the error previously posted.

**Comment by guybedford** [comment]
@MAPESO I would suggest using `npm install -g ncc` and then `ncc run index.js` for testing further to ensure we are directly testing ncc bugs.

**Comment by MAPESO** [comment]
@guybedford  This is very strange, my output looks different from yours 😕 

```json
ncc: Module directory "/Users/mark/db-serverless/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/Users/mark/db-serverless/node_modules/node-fetch/lib" attempted to require "encoding" but could not be resolved, assuming external.
ncc: Module directory "/Users/mark/db-serverless/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
ncc: Module directory "/Users/mark/db-serverless/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/Users/mark/db-serverless/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
   1kB  dist/src/load.d.ts
   1kB  dist/protos/google/api/annotations.proto
   2kB  dist/src/load.js.map
   2kB  dist/src/index.d.ts
   2kB  dist/src/index.js.map
   2kB  dist/protos/update.sh
   2kB  dist/protos/google/protobuf/empty.proto
   3kB  dist/protos/google/firestore/v1/common.proto
   3kB  dist/protos/google/firestore/v1beta1/common.proto
   3kB  dist/protos/google/type/latlng.proto
   4kB  dist/protos/google/rpc/status.proto
   4kB  dist/protos/google/protobuf/struct.proto
   4kB  dist/protos/google/protobuf/wrappers.proto
   5kB  dist/protos/google/firestore/v1beta1/document.proto
   5kB  dist/protos/google/firestore/v1/document.proto
   6kB  dist/protos/google/firestore/v1/query.proto
   6kB  dist/protos/google/protobuf/timestamp.proto
   6kB  dist/protos/google/firestore/v1beta1/query.proto
   6kB  dist/protos/google/protobuf/any.proto
  10kB  dist/protos/google/firestore/v1beta1/write.proto
  10kB  dist/protos/google/firestore/v1/write.proto
  15kB  dist/protos/google/api/http.proto
  26kB  dist/protos/google/firestore/v1/firestore.proto
  27kB  dist/protos/google/firestore/v1beta1/firestore.proto
 127kB  dist/protos/firestore_proto_api.d.ts
 272kB  dist/roots.pem
7871kB  dist/index.js
8425kB  [52044ms] - ncc 0.15.2
(node:9061) UnhandledPromiseRejectionWarning: Error: db-serverless package.json is not node-pre-gyp ready:
package.json must declare these properties: 
binary.module_name
binary.module_path
binary.host
    at Object.validate_config (/Users/mark/db-serverless/dist/index.js:147687:15)
    at Object.module.exports.exports.find (/Users/mark/db-serverless/dist/index.js:44259:15)
    at Object.module.exports.module.exports.interfaces.google.firestore.v1beta1.Firestore.retry_codes.idempotent (/Users/mark/db-serverless/dist/index.js:24492:12)
    at __webpack_require__ (/Users/mark/db-serverless/dist/index.js:22:30)
    at Object.module.exports.Object.setPrototypeOf.__proto__ (/Users/mark/db-serverless/dist/index.js:139493:12)
    at __webpack_require__ (/Users/mark/db-serverless/dist/index.js:22:30)
    at Object.module.exports.Object.defineProperty.value (/Users/mark/db-serverless/dist/index.js:174202:27)
    at __webpack_require__ (/Users/mark/db-serverless/dist/index.js:22:30)
    at Object.module.exports.module.exports.out (/Users/mark/db-serverless/dist/index.js:128527:14)
    at __webpack_require__ (/Users/mark/db-serverless/dist/index.js:22:30)
(node:9061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

btw The result of the code line **99153** is a firebase function
```js
    function FirebaseNamespace() {
        // Hack to prevent Babel from modifying the object returned as the default admin namespace.
        /* tslint:disable:variable-name */
        this.__esModule = true;
        /* tslint:enable:variable-name */
        this.credential = firebaseCredential;
        this.SDK_VERSION = '7.0.0';
        /* tslint:disable */
        // TODO(jwenger): Database is the only consumer of firebase.Promise. We should update it to use
        // use the native Promise and then remove this.
        this.Promise = Promise;
        this.INTERNAL = new FirebaseNamespaceInternals(this);
    }
```

**Comment by MAPESO** [comment]
@guybedford 
> To hide this warning and ensure your app does not break, you need to add the
following code to your app before calling any other Cloud Firestore methods:

there must be some way in which `ncc` can solve that without us reaching that alternative. It is not practical for an average user to have to do that configuration before using `firestore` in` now`

**Comment by guybedford** [comment]
@MAPESO thanks for providing the new details here. Unfortunately that's not quite the right source line as the debug output there has the corresponding line of the parent call to `find()` as `db-serverless/dist/index.js:24492`, not line `99153`. Can you share that code here rather? You should be able to see an explicit `.find()` style call in that section and that is what we want to work out.

It is quite odd that we are getting different errors, I'm not sure why that is the case. If you have any ideas where our workflows might be differing here let me know too. And thanks for your help tracking this down!

> there must be some way in which ncc can solve that without us reaching that alternative. It is not practical for an average user to have to do that configuration before using firestore in now

Note I get this error both with and without ncc - that is, it seems this is a Firestore-specific warning about the workflow and nothing to do with ncc as far as I can tell.

**Comment by guybedford** [comment]
@MAPESO are you running on MacOS?

**Comment by MAPESO** [comment]
> are you running on MacOS ?

Yes : ) these are the specifications of my computer

<img width="598" alt="Screen Shot 2019-03-15 at 11 59 20" src="https://user-images.githubusercontent.com/16585386/54452086-e13aea80-4719-11e9-9565-dd2da248b7be.png">


> Note I get this error both with and without ncc - that is, it seems this is a Firestore-specific warning about the workflow and nothing to do with ncc as far as I can tell.

But firebase example work directly with `node` and express etc 🤔 

Result of the **24492** code line
```js
    binary.find(path.resolve(path.join(__dirname, '../package.json')));
```

> If you have any ideas where our workflows might be differing here let me know too.

This is a clone of my repository, I hope that can help. Remember to use your firebase keys

[repository](https://github.com/MAPESO/db-serverless)

**Comment by MAPESO** [comment]
@guybedford we moved this error to #317  I offer a better explanation : )
