### ISSUE TITLE
`require('express')` + any syntax error causes unhandled rejection

### ISSUE THREAD

**Issue by igorklopov** [zeit/ncc#332]
```
require('express');
await fn();
```
also
```
require('express');
{
```
also
```
require('express');
break;
```

**Comment by guybedford** [comment]
Are you sure this is running the latest ncc with the fix from https://github.com/zeit/ncc/pull/324 (ncc 0.17.0). I just tried this on the latest build and the errors seem to display correctly here.

**Comment by igorklopov** [comment]
@guybedford I confirm. Just checked again. This script reproduces it from scratch:
```
npm init -y
npm i @zeit/ncc@0.17.0
echo -e "require('express');\nbreak;" > index.js
./node_modules/.bin/ncc build index.js
```

**Comment by igorklopov** [comment]
```
+ @zeit/ncc@0.17.0
added 1 package and audited 1 package in 0.628s
found 0 vulnerabilities

Error: Hash: f0cb339b46719d2d303b
Version: webpack 5.0.0-alpha.9
Time: 105ms
Built at: 03/31/2019 8:32:49 PM
   Asset     Size  Chunks  Chunk Names
index.js  2.1 KiB   {404}  main
Entrypoint main = index.js
[950] ./index.js 782 bytes {404} [built] [failed] [1 error]

ERROR in ./index.js
Module build failed (from ./node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js):
SyntaxError: Unexpected token (1:3)
    at Object.re.raise (evalmachine.<anonymous>:1:179108)
    at Object.V.unexpected (evalmachine.<anonymous>:1:135378)
    at Object.V.semicolon (evalmachine.<anonymous>:1:135092)
    at Object.Q.parseExpressionStatement (evalmachine.<anonymous>:1:145410)
    at Object.Q.parseStatement (evalmachine.<anonymous>:1:139585)
    at Object.parseStatement (evalmachine.<anonymous>:1:30297)
    at Object.parseStatement (evalmachine.<anonymous>:1:575710)
    at Object.Q.parseTopLevel (evalmachine.<anonymous>:1:136703)
    at Object.parse (evalmachine.<anonymous>:1:133032)
    at Function.parse (evalmachine.<anonymous>:1:133799)

    at compiler.close.n (evalmachine.<anonymous>:3:1349901)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by igorklopov** [comment]
However i expect
```
ERROR in ./index.js 2:0
Module parse failed: Unsyntactic break (2:0)
You may need an appropriate loader to handle this file type.
| require('');
> break;
|

    at compiler.close.n (evalmachine.<anonymous>:3:1349901)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by igorklopov** [comment]
@guybedford btw it works well with 0.16.1. This one prints a correct message:
```
npm init -y
npm i @zeit/ncc@0.16.1
echo $"require('express');\nbreak;" > index.js
./node_modules/.bin/ncc build index.js
```

**Comment by guybedford** [comment]
Ahh I see. Yes the asset relocator does a parse, but does not provide syntax highlighted errors. Marking as an enhancement.

**Comment by igorklopov** [comment]
Thanks! Yeah, it is not unhandled rejection in 0.17.0, only wrong message.

**Comment by guybedford** [comment]
Implemented in https://github.com/zeit/webpack-asset-relocator-loader/pull/63.
