### ISSUE TITLE
Failed to build fluent-ffmpeg with Error: Can't resolve './lib-cov/fluent-ffmpeg' 

### ISSUE THREAD

**Issue by styfle** [zeit/ncc#358]
## Steps to reproduce

```
git clone https://github.com/styfle/ncc-bug-fluent-ffmpeg
cd ncc-bug-fluent-ffmpeg
yarn
ncc build index.js
```

## Output

```
ncc: Version 0.18.1
ncc: Compiling file index.js
Error: Hash: 010bf5d256da3ab07bed
Version: webpack 5.0.0-alpha.9
Time: 93ms
Built at: 04/24/2019 5:21:04 PM
   Asset     Size  Chunks  Chunk Names
index.js  301 KiB   {404}  main
Entrypoint main = index.js
 [64] external "util" 42 bytes {404}
[123] ./node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js 6.31 KiB {404}
[170] ./node_modules/fluent-ffmpeg/lib/options/misc.js 933 bytes {404}
[172] ./node_modules/fluent-ffmpeg/lib/options/output.js 3.84 KiB {404}
[200] ./node_modules/fluent-ffmpeg/lib/options/videosize.js 7.58 KiB {404}
[300] ./node_modules/fluent-ffmpeg/lib/options/audio.js 3.86 KiB {404}
[318] ./index.js 631 bytes {404}
[417] ./node_modules/fluent-ffmpeg/lib/options/custom.js 6.54 KiB {404}
[421] external "http" 42 bytes {404}
[476] ./node_modules/fluent-ffmpeg/lib/options/video.js 4.02 KiB {404}
[477] ./node_modules/fluent-ffmpeg/lib/options/inputs.js 3.89 KiB {404}
[485] external "events" 42 bytes {404}
[573] ./node_modules/fluent-ffmpeg/lib/utils.js 12.9 KiB {404}
[589] external "path" 42 bytes {404}
[805] ./node_modules/fluent-ffmpeg/index.js 117 bytes {404}
    + 14 hidden modules

ERROR in ./node_modules/fluent-ffmpeg/index.js 1:48-82
Module not found: Error: Can't resolve './lib-cov/fluent-ffmpeg' in '/Users/styfle/Code/foo/ncc-bug-fluent-ffmpeg/node_modules/fluent-ffmpeg'
 @ ./index.js 1:15-39

    at compiler.close.n (evalmachine.<anonymous>:3:1350162)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by styfle** [comment]
One possible solution is setting the `FLUENTFFMPEG_COV` variable.

See this comment: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-305408048

**Comment by styfle** [comment]
@guybedford This is still a problem, even on the master branch with #365 merged

**Comment by guybedford** [comment]
@styfle can you share what error you are getting here? Also did you run `ncc cache clean`?

**Comment by styfle** [comment]
@guybedford Yes I ran `ncc cache clean`. Its the same error.


```
ncc: Version 0.18.1
ncc: Compiling file index.js
Error: Hash: 98c830f22645a5adc6e7
Version: webpack 5.0.0-alpha.9
Time: 478ms
Built at: 04/30/2019 11:22:55 AM
   Asset     Size  Chunks  Chunk Names
index.js  301 KiB   {404}  main
Entrypoint main = index.js
 [64] external "util" 42 bytes {404} [built]
[156] ./node_modules/fluent-ffmpeg/lib/options/custom.js 6.54 KiB {404} [built]
[264] ./node_modules/fluent-ffmpeg/index.js 117 bytes {404} [built]
[371] ./node_modules/fluent-ffmpeg/lib/options/videosize.js 7.58 KiB {404} [built]
[421] external "http" 42 bytes {404} [built]
[485] external "events" 42 bytes {404} [built]
[493] ./node_modules/fluent-ffmpeg/lib/options/audio.js 3.86 KiB {404} [built]
[495] ./node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js 6.31 KiB {404} [built]
[540] ./node_modules/fluent-ffmpeg/lib/options/inputs.js 3.89 KiB {404} [built]
[563] ./node_modules/fluent-ffmpeg/lib/options/misc.js 933 bytes {404} [built]
[589] external "path" 42 bytes {404} [built]
[604] ./node_modules/fluent-ffmpeg/lib/utils.js 12.9 KiB {404} [built]
[740] ./node_modules/fluent-ffmpeg/lib/options/output.js 3.84 KiB {404} [built]
[746] ./index.js 631 bytes {404} [built]
[939] ./node_modules/fluent-ffmpeg/lib/options/video.js 4.02 KiB {404} [built]
    + 14 hidden modules

ERROR in ./node_modules/fluent-ffmpeg/index.js 1:48-82
Module not found: Error: Can't resolve './lib-cov/fluent-ffmpeg' in '/Users/styfle/Code/foo/ncc-bug-fluent-ffmpeg/node_modules/fluent-ffmpeg'
 @ ./index.js 1:15-39

    at compiler.close.n (evalmachine.<anonymous>:3:1350279)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by styfle** [comment]
I works, I forgot to do `yarn install` first 😄

**Comment by Yasgur99** [comment]
still an issue for me. any solution?
