### ISSUE TITLE
firebase admin - TypeError: process.off is not a function

### ISSUE THREAD

**Issue by MAPESO** [zeit/ncc#367]
**OS:** 10.14.4
**ncc:** 0.18.1
**firebase-admin:** Firebase Admin Node.js SDK v7.3.0

ncc still does not quite finish working well with **firebase-admin**. I manage to connect with my db but `ncc` returns an error once I run `ncc run xxx.js`

```
TypeError: process.off is not a function
    at ChildProcess.exit (evalmachine.<anonymous>:1:33251)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

## Steps to reproduce 🐛 

```sh
git clone https://github.com/MAPESO/ncc-bug-firebase
cd ncc-bug-firebase
yarn install  # dependency installation
ncc run index.js   # note the error output
```

**Comment by guybedford** [comment]
When I run this case I get the following error:

```
ERROR in ./index.js 4:23-58
Module not found: Error: Can't resolve './serviceAccountKey.json' in '/home/guybedford/Projects/ncc/ncc-bug-firebase'

    at compiler.close.n (evalmachine.<anonymous>:3:1350237)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Do I need to create a Firebase account and configure it?

**Comment by guybedford** [comment]
@MAPESO is this issue resolved?
