### ISSUE TITLE
Error: new Buffer() on nodejs10.x (AWS Lambda)

### ISSUE THREAD

**Issue by simlu** [zeit/ncc#391]
We're seeing problems where ncc compiles `new Buffer(...)` and that then crashes on nodejs10.x (AWS Lambda). I'm still investigating and will update as we find more details.

**Comment by NathanielHill** [comment]
I wonder if this error I'm getting from a Lambda could be related:

```
(node:1) Warning: N-API is an experimental feature and could change at any time.
Internal Server Error:  TypeError: bu.mask is not a function
    at mask (/var/task/api/report/index.js:96757:15)
    at Function.frame (/var/task/api/report/index.js:234498:7)
    at Sender.send (/var/task/api/report/index.js:234686:16)
    at WebSocket.send (/var/task/api/report/index.js:243761:18)
    at WebSocketTransport.send (/var/task/api/report/index.js:211478:14)
    at Connection._rawSend (/var/task/api/report/index.js:61352:21)
    at Connection.send (/var/task/api/report/index.js:61338:21)
    at Function.create (/var/task/api/report/index.js:102294:22)
    at Launcher.launch (/var/task/api/report/index.js:162759:37)
    at <anonymous>
```
I know `bu` is `bufferUtil` from looking at the compiled lambda, but no idea why it's not being imported correctly. Perhaps that's not the problem, and it's breaking due to a difference in the `Buffer` implementation in Node 10?

@styfle

**Comment by styfle** [comment]
@simlu Is there an error message?

@NathanielHill Perhaps your package using `N-API` expects Node 10 instead of Node 8. Can you reproduce the issue when running `ncc run index.js` with your js file?

**Comment by NathanielHill** [comment]
@styfle I don't think these are related. I've opened a seperate issue #413. Doesn't appear to be a Node 10 issue at all.
