### ISSUE TITLE
Sequelize regression

### ISSUE THREAD

**Issue by guybedford** [zeit/ncc#397]
On ncc 0.17.0-beta there is a Sequelize regression - 

```
/tmp/c39330374ab30c5bc8e34ebff9ef926e/index.js:48516
  const e = new Error('Cannot find module "' + id + '".');
            ^
Error: Cannot find module "./dialects//data-types".
    at Object.<anonymous> (/tmp/c39330374ab30c5bc8e34ebff9ef926e/index.js:48516:13)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.module.exports.module.exports (/tmp/c39330374ab30c5bc8e34ebff9ef926e/index.js:37855:19)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.<anonymous> (/tmp/node_modules/sequelize/lib/utils.js:3:19)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.<anonymous> (/tmp/c39330374ab30c5bc8e34ebff9ef926e/index.js:49217:15)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.module.exports.Object.defineProperty.value (/tmp/node_modules/sequelize/index.js:8:18)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.<anonymous> (/tmp/test/integration/sequelize.js:1:19)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at startup (/webpack/bootstrap:33:1)
    at /webpack/bootstrap:39:1
    at Object.<anonymous> (/tmp/c39330374ab30c5bc8e34ebff9ef926e/index.js:45:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by guybedford** [comment]
It turns out this is caused directly by the lack of support for wildcards in require statements, as in https://github.com/zeit/webpack-asset-relocator-loader/issues/36.
