### ISSUE TITLE
can't support argon2

### ISSUE THREAD

**Issue by zuohuadong** [zeit/ncc#464]
https://github.com/ranisalt/node-argon2

```
/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201473
  throw new Error('No native build was found for ' + target)
  ^

Error: No native build was found for platform=darwin arch=x64 runtime=node abi=72 uv=1 libc=glibc
    at Function.module.exports.load.path (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201473:9)
    at load (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:201437:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:217784:81)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:259301:18)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:411873:10)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:210789:17)
    at webpack_require (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:22:30)
    at startup (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:39:19)
    at /Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:45:18
    at Object.<anonymous> (/Users/ims/Desktop/guanjie/ganker/dist/addons/basic/index.js:48:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
```

**Comment by AkhilMukkamala** [comment]
Facing similar issue with Argon Package, on node v12.13.0

**Comment by canyuegongzi** [comment]
Facing similar issue with Argon Package, on node v16
