### ISSUE TITLE
not support shelljs package

### ISSUE THREAD

**Issue by hugohua** [zeit/ncc#476]
(node:110708) UnhandledPromiseRejectionWarning: TypeError: shelljs_1.default.exec is not a function
    at exeList.forEach.item (evalmachine.<anonymous>:7230:42)
    at Array.forEach (<anonymous>)
    at addCommit (evalmachine.<anonymous>:7229:13)
    at inquirer_1.default.prompt.then (evalmachine.<anonymous>:7333:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:110708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:110708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rommguy** [comment]
Same here

**Comment by DanielSinclair** [comment]
Likewise. NCC seems to be dropping [this](https://github.com/shelljs/shelljs/blob/aed6d994b57bccea313e85eeaa9650077b12f4de/shell.js#L23) require structure. Shell is built around an interesting plugin registration architecture that flies over my head; the conflict with ncc could be somewhere there too. Maybe @nfischer has pointers?

**Comment by nfischer** [comment]
Are you using some sort of bundler? Do you see the same error for other shelljs commands (ex. `shell.echo()`)?

**Comment by wenerme** [comment]
@nfischer Same error

```
(node:58118) UnhandledPromiseRejectionWarning: TypeError: shelljs__WEBPACK_IMPORTED_MODULE_0__.echo is not a function
    at /Users/wener/temp/next/wapi/dist/index.js:6204:46
    at Generator.next (<anonymous>)
    at /Users/wener/temp/next/wapi/dist/index.js:6197:71
    at new Promise (<anonymous>)
    at module.exports.819.__awaiter (/Users/wener/temp/next/wapi/dist/index.js:6193:12)
    at main (/Users/wener/temp/next/wapi/dist/index.js:6203:12)
    at /Users/wener/temp/next/wapi/dist/index.js:6216:15
    at Generator.next (<anonymous>)
    at /Users/wener/temp/next/wapi/dist/index.js:6197:71
    at new Promise (<anonymous>)
(node:58118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:58118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
