### ISSUE TITLE
`probot` errors

### ISSUE THREAD

**Issue by swinton** [zeit/ncc#480]
:wave: I'm encountering an error when running a compiled project that has [Probot](https://github.com/probot/probot) as a dependency:

## Details

`ncc` version: 0.20.5

**Source:**

```javascript
const { Application } = require('probot')

```

**Crashes with:**

```
/Users/swinton/scratch/probot-app/dist/index.js:26154
        self.store = __ncc_wildcard$0(storeName).create(args);
                                                ^

TypeError: Cannot read property 'create' of undefined
    at Object.caching (/Users/swinton/scratch/probot-app/dist/index.js:26154:49)
    at Object.createDefaultCache (/Users/swinton/scratch/probot-app/dist/index.js:15375:36)
    at Object.module.exports.module.exports (/Users/swinton/scratch/probot-app/dist/index.js:51797:21)
    at __webpack_require__ (/Users/swinton/scratch/probot-app/dist/index.js:22:30)
    at Object.<anonymous> (/Users/swinton/scratch/probot-app/dist/index.js:8599:1)
    at __webpack_require__ (/Users/swinton/scratch/probot-app/dist/index.js:22:30)
    at startup (/Users/swinton/scratch/probot-app/dist/index.js:37:19)
    at /Users/swinton/scratch/probot-app/dist/index.js:43:18
    at Object.<anonymous> (/Users/swinton/scratch/probot-app/dist/index.js:46:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

___
**Package.json:**

```json
{
  "name": "probot-app",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "ncc build ./index.js"
  },
  "license": "ISC",
  "dependencies": {
    "probot": "^9.5.1"
  },
  "devDependencies": {
    "@zeit/ncc": "^0.20.5"
  }
}
```

**Comment by imjohnbo** [comment]
@swinton, what version of Node are you running? I wasn't able to reproduce this with Node 11.11.0 at https://github.com/imjohnbo/probot-playground. 👀

**Comment by swinton** [comment]
> what version of Node are you running? 

 11.11.0 also...


> I wasn't able to reproduce this with Node 11.11.0 at https://github.com/imjohnbo/probot-playground. 

Strange. I cloned your repo and i’m still getting the error above with the compiled artifact from ncc 🤔

**Comment by imjohnbo** [comment]
Strange indeed! Check out these [successful build results](https://github.com/imjohnbo/probot-playground/commit/2bf8a903ad6426398e5337e61531994574022a00/checks?check_suite_id=257154351) from a GitHub Actions runner. 

I'm interested in what is causing a local failure for you.

**Comment by swinton** [comment]
> Strange indeed! Check out these [successful build results](https://github.com/imjohnbo/probot-playground/commit/2bf8a903ad6426398e5337e61531994574022a00/checks?check_suite_id=257154351) from a GitHub Actions runner.
> 
> I'm interested in what is causing a local failure for you.

Thanks @imjohnbo.

I [forked your repo](https://github.com/swinton/probot-playground) and [edited the `build.yml` to actually run the file generated by `ncc`](https://github.com/swinton/probot-playground/commit/06ffa74c1c0e187e1964ecccdbeff751bc43a128), when [Actions runs the file](https://github.com/swinton/probot-playground/runs/259435318), the same error [as above](https://github.com/zeit/ncc/issues/480#issue-504013825) is [reported](https://github.com/swinton/probot-playground/runs/259435318#step:4:1):

```
TypeError: Cannot read property 'create' of undefined
    at Object.caching (/home/runner/work/probot-playground/probot-playground/dist/index.js:26159:49)
    at Object.createDefaultCache (/home/runner/work/probot-playground/probot-playground/dist/index.js:15376:36)
    at Object.module.exports.module.exports (/home/runner/work/probot-playground/probot-playground/dist/index.js:51793:21)
    at __webpack_require__ (/home/runner/work/probot-playground/probot-playground/dist/index.js:22:30)
    at Object.<anonymous> (/home/runner/work/probot-playground/probot-playground/dist/index.js:8599:25)
    at __webpack_require__ (/home/runner/work/probot-playground/probot-playground/dist/index.js:22:30)
    at startup (/home/runner/work/probot-playground/probot-playground/dist/index.js:37:19)
    at /home/runner/work/probot-playground/probot-playground/dist/index.js:43:18
    at Object.<anonymous> (/home/runner/work/probot-playground/probot-playground/dist/index.js:46:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by ezyang** [comment]
I'm also affected by this.

**Comment by ibraelillo** [comment]
Any update on this? I'm also facing this issue

**Comment by swinton** [comment]
@imjohnbo did some more research and was able to [isolate this issue to `cache-manager`](https://github.com/imjohnbo/cache-manager-zeit-ncc/runs/280961328#step:4:14):

### Source:

```javascript
var cacheManager = require('cache-manager');
var memoryCache = cacheManager.caching({store: 'memory', max: 100, ttl: 10/*seconds*/});
var ttl = 5;
```

**Comment by imjohnbo** [comment]
Would you all mind testing against [this Probot sha](https://github.com/probot/probot/commit/9ac0ee1ca95320b6d529fc4484be8565e872b737)? Release should be cut soon. Fingers crossed that that fixes it.

**Comment by imjohnbo** [comment]
Probot 9.6.5 was released today, including [this commit](https://github.com/probot/probot/pull/1066#issuecomment-554806319), @swinton! This [seems to fix](https://github.com/imjohnbo/probot-playground/commit/0afdecc1203582506e08211dd083c71d85b61783/checks?check_suite_id=316284870) the crash you reported [above](https://github.com/zeit/ncc/issues/480#issue-504013825). 🎉

**Comment by robvanderleek** [comment]
It's now fixed for me (complied Probot app as GH action) :-)

**Comment by swinton** [comment]
Thanks for figuring this one out, @imjohnbo. Seems like this is good to close? 🎉 


___
> It's now fixed for me (complied Probot app as GH action) :-)

✨ Great to hear! In case it helps, there’s also https://github.com/probot/actions-adapter which will convert a Probot app into an Action.
