### ISSUE TITLE
Cannot find module '.../node_modules@zeitnccdistncccli.js'

### ISSUE THREAD

**Issue by petarpetrovt** [zeit/ncc#502]
Running the following command fails.

```
node node_modules\@zeit\ncc\dist\ncc\cli.js build index.js -m -o ../executor
```
or
```
node ncc build index.js -o ../executor
```

It works only the first time after installing NPM packages.
The second time `cli.js` in `...\dist\ncc\cli.js` gets replaced with `cli.js.cache`

Error:
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/executor/node_modules@zeitnccdistncccli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! executor@0.0.1 build: `node node_modules\@zeit\ncc\dist\ncc\cli.js build index.js -m`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the executor@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-02-05T19_27_03_502Z-debug.log
```

**Comment by petarpetrovt** [comment]
Seems to be happening only when `-o` argument is provided and its the current directory.
