### ISSUE TITLE
ncc 0.21.1 HTML template ‘ejs’ is not supported 

### ISSUE THREAD

**Issue by ShareQiu1994** [zeit/ncc#514]
I am compiling nestjs project with NCC，After compiling, I found that it couldn't run.

When you visit http://localhost:3000 you'll see the following error
```
Error: Cannot find module 'ejs'
Require stack:
- D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at new View (D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:7:5400069)
    at Function.render (D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:9:20917)
    at ServerResponse.render (D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:7:322305)
    at ExpressAdapter.render (D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:1:241285)
    at RouterResponseController.render (D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:7:6476472)
    at async D:\github\LBF_Earth_SourceCodeServer_ncc_dist\index.js:1:2846438
```
my main.js
```
  app.setViewEngine('ejs'); 
  app.setBaseViewsDir(join(__dirname, '..', `'views'));`
```

I saw the issues
> https://github.com/zeit/ncc/issues/323

I tried to modify main.js, which works, but it may not be a good solution
```
  app.engine('ejs', require('ejs').__express); 
  app.setBaseViewsDir(join(__dirname, '..', 'views'));
```

Nestjs uses express as the HTTP framework

**Comment by ShareQiu1994** [comment]
ejs  Version 3.0.1 solves this problem...

"ejs": "^3.0.1",
