### ISSUE TITLE
Error: Cannot find module 'asn1.js'

### ISSUE THREAD

**Issue by crazy-max** [zeit/ncc#538]
Getting this error with [asn1.js](https://www.npmjs.com/package/asn1):

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'asn1.js'
Require stack:
- /home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at o (/home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:1892:200)
    at /home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:1892:391
    at Object.<anonymous> (/home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:32512:27)
    at Object.108.../../config (/home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:33029:4)
    at o (/home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:1892:340)
    at /home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js:1892:391 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/crazy-max/ghaction-import-gpg/v1/dist/index.js'
  ]
}
```

This module is required by [openpgpjs](https://github.com/openpgpjs/openpgpjs/blob/2c6cbc4cb2d4ada62345a74218a8543f71f26c78/package.json#L86) and used in the GitHub Action [ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg).

Current workaround, add the following deps in `node_modules`:

* asn1.js
* bn.js
* inherits
* minimalistic-assert
* safer-buffer

Looks like they are left out of the bundle by ncc.

Reproduce with:

```
git clone https://github.com/crazy-max/ghaction-import-gpg.git
cd ghaction-import-gpg/
npm install
npm run build
rm -rf node-modules/
node dist/index.js
```

**Comment by vordimous** [comment]
I am seeing this issue using also with my implementation of openpgpjs.

**Comment by vordimous** [comment]
@crazy-max  i was able to remove opengpg as a dependency using [this example](https://stackoverflow.com/questions/8750780/encrypting-data-with-a-public-key-in-node-js) as a workaround for now.

**Comment by vordimous** [comment]
I found a workaround by forking the repo and updating their grunt script to include asn1.js

`"openpgp": "https://github.com/vordimous/openpgpjs.git",`

**Comment by satoruk** [comment]
@vordimous 
I think it's a smart idea ✨ 
Would you be planning to send a PR to https://github.com/openpgpjs/openpgpjs ?

**Comment by vordimous** [comment]
opened a [PR](https://github.com/openpgpjs/openpgpjs/pull/1163)

I guess we will see if they want to change the way the lib is packaged.

**Comment by satoruk** [comment]
I hope it's accepted or resolved in some other way.

**Comment by vordimous** [comment]
There are some new workaround options from the openpgp dev on my [PR](https://github.com/openpgpjs/openpgpjs/pull/1163)
