### ISSUE TITLE
`auth0` errors

### ISSUE THREAD

**Issue by rauchg** [zeit/ncc#9]
ncc version: 0.0.4

Source:

```js
var AuthenticationClient = require("auth0").AuthenticationClient;

var auth0 = new AuthenticationClient({
  domain: "{YOUR_ACCOUNT}.auth0.com",
  clientId: "{OPTIONAL_CLIENT_ID}"
});
```

crashes with:

```
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
(node:30620) UnhandledPromiseRejectionWarning: Error: Illegal reassignment to import 'commonjsHelpers'
    at error (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:13349:9)
    at MemberExpression$$1.disallowNamespaceReassignment (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:11372:26)
    at MemberExpression$$1.deoptimizePath (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:11340:18)
    at AssignmentExpression.bind (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:9920:19)
    at ExpressionStatement$$1.NodeBase.bind (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:9183:23)
    at IfStatement.NodeBase.bind (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:9183:23)
    at IfStatement.bind (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:10807:31)
    at Program.NodeBase.bind (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:9179:31)
    at Module.bindReferences (/usr/local/lib/node_modules/@zeit/ncc/node_modules/rollup/dist/rollup.js:13303:18)
(node:30620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by guybedford** [comment]
This is a bug in rollup-commonjs caused in `node_modules/formidable/lib/incoming_form.js` with the following code:

```js
if (global.GENTLY) require = GENTLY.hijack(require);
```

which is converted to:

```js
import * as commonjsHelpers from 'commonjs-helpers';
if (commonjsHelpers.global.GENTLY) commonjsHelpers.require = commonjsHelpers.global.GENTLY.hijack(require);
```

I think the best fix would be to have the CommonJS plugin entirely ignore assignments when doing dynamic require replacements to avoid this bug.

Working on the PR now.

**Comment by guybedford** [comment]
PR https://github.com/rollup/rollup-plugin-commonjs/pull/359

**Comment by guybedford** [comment]
(and added to the #merges fork)

**Comment by guybedford** [comment]
With the merge made, the remaining issue is a cycle bug.
